// test-api.http

GET http://localhost:8000/api/ratings/

###          

GET http://localhost:8000/api/ratings/12

###

PUT http://localhost:8000/api/ratings/12
content-type: application/json

{
    "rate":2
}
// ...